### ISSUE TITLE
(Rinkeby) Wrong BAT token address?

### ISSUE THREAD

**Issue by pablofullana** [protofire/tokens-faucet#6]
After adding BAT to MetaMask via the `Add tokens -> Search` feature:

![Image 2020-02-17 at 4 32 50 PM](https://user-images.githubusercontent.com/1939415/74681850-32155780-51a3-11ea-8ca5-529601f966c6.png)

Despite that, when I open my account in Etherscan:

![Image 2020-02-17 at 4 33 43 PM](https://user-images.githubusercontent.com/1939415/74681887-49544500-51a3-11ea-91b2-2f68abe4e607.png)

So I got my BATs, but not the BAT MM "knowns"?

**Comment by fvictorio** [comment]
When you add tokens in MM using the search feature, the addresses added are for those tokens in the mainnet, so they don't make sense in any testnet (unless the token is deployed in the same address, which is possible but most projects don't do).

**Comment by pablofullana** [comment]
😒
